import { useQuery } from "@tanstack/react-query";
import { Clock3, MapPin, Route } from "lucide-react";
import { useEffect } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { api } from "../api";
import { Empty, ErrorState, Loading, Status, formatDate } from "../components";
import { useWorkspace } from "../state";

export function TimelinePage(){const {caseId=""}=useParams();const [params]=useSearchParams();const {selectedId,setSelectedId}=useWorkspace();const query=useQuery({queryKey:["timeline",caseId],queryFn:()=>api.timeline(caseId)});useEffect(()=>{const id=params.get("evidence");if(id)setSelectedId(id)},[params,setSelectedId]);if(query.isLoading)return <Loading/>;if(query.error)return <ErrorState message={query.error.message}/>;const items=query.data?.items??[];return <div className="workspace"><div className="workspace-heading"><div><p className="eyebrow">CHRONOLOGY</p><h1>Evidence timeline</h1><p>Selected timestamps remain labelled by source, timezone status, and confidence.</p></div></div>{items.length===0?<Empty title="Timeline unavailable" body="Add evidence to construct a qualified chronology."/>:<div className="timeline">{items.map((item,index)=><div key={item.id}>{item.derived_leg&&<div className="travel-leg"><Route size={16}/><span><b>Derived leg:</b> {item.derived_leg.distance_km.toFixed(1)} km · {Math.round(item.derived_leg.interval_seconds/60)} min · {item.derived_leg.speed_kmh===null?"speed skipped":`${item.derived_leg.speed_kmh.toFixed(1)} km/h`}</span></div>}<article className={item.id===selectedId?"timeline-event selected":"timeline-event"} onClick={()=>setSelectedId(item.id)}><div className="timeline-index">{index+1}</div><img src={`/api/v1/evidence/${item.id}/thumbnail`} alt=""/><div className="timeline-main"><div><strong>{item.evidence_id}</strong><span>{item.original_filename}</span></div><time><Clock3 size={15}/>{formatDate(item.metadata.timeline_timestamp_utc??item.metadata.timeline_timestamp_raw)}</time><div className="timeline-tags"><Status value={item.metadata.timeline_timestamp_confidence}/><span>{item.metadata.timeline_timestamp_source.replaceAll("_"," ")}</span><span>{item.metadata.timeline_timezone_status.replaceAll("_"," ")}</span>{item.metadata.gps_latitude!==null&&<span><MapPin size={13}/>Location available</span>}</div></div><div className="timeline-actions"><span>{item.finding_count} findings</span><Link to={`../evidence?evidence=${item.id}`}>Inspect →</Link></div></article></div>)}</div>}</div>}

