export type Case = { id:string; case_number:string; name:string; description:string; analyst_name:string; status:string; case_timezone:string|null; created_at:string; updated_at:string };
export type Metadata = { raw_metadata:Record<string,unknown>; datetime_original_raw:string|null; datetime_digitized_raw:string|null; gps_datetime_raw:string|null; timeline_timestamp_raw:string|null; timeline_timestamp_utc:string|null; timeline_timezone_status:string; timeline_timestamp_source:string; timeline_timestamp_confidence:string; timestamp_selection_reason:string; gps_latitude:number|null; gps_longitude:number|null; gps_altitude:number|null; camera_make:string|null; camera_model:string|null; lens_model:string|null; software:string|null; extraction_warnings:string[] };
export type Evidence = { id:string; case_id:string; evidence_id:string; original_filename:string; mime_type:string; file_size:number; width:number; height:number; acquired_at:string; acquired_by:string; sha256_acquisition:string; sha256_current:string; integrity_status:string; review_status:string; metadata:Metadata; finding_count:number; highest_severity:string|null; derived_leg?:{distance_km:number;interval_seconds:number;speed_kmh:number|null}|null };
export type Finding = { id:string; analysis_run_id:string; evidence_file_id:string|null; related_evidence_file_id:string|null; category:string; severity:string; rule_id:string; rule_version:string; title:string; explanation:string; supporting_data_json:string; reviewer_status:string; current_disposition:string|null; created_at:string };
export type AnalysisRun = { id:string; case_id:string; analyzer_version:string; rule_set_version:string; application_version:string; configuration_json:string; configuration_sha256:string; status:string; started_at:string; completed_at:string|null };
export type CustodyEvent = { id:string; case_id:string; evidence_file_id:string|null; event_type:string; actor:string; timestamp:string; details_json:string };
export type Report = { id:string; case_id:string; analysis_run_id:string; sha256:string; generated_at:string; generated_by:string };
export type Page<T> = { items:T[]; total:number; page:number; page_size:number };

